namespace SpriteKind {
    export const object = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    pause(100)
    Car_Crash.setPosition(1000, 0)
    scene.cameraShake(4, 500)
    Car.startEffect(effects.fire, 500)
    Car_Crash.startEffect(effects.fire, 500)
})
let Car_Crash: Sprite = null
let Car: Sprite = null
info.setLife(3)
Car = sprites.create(img`
    . . . . . . e e c c e e . . . . 
    . . . . . e 2 2 2 2 2 2 e . . . 
    . . . . 2 c 2 2 2 2 2 2 c 2 . . 
    . . . e 2 c 4 2 2 2 2 2 c 2 e . 
    . . . f 2 2 4 2 2 2 2 2 c 2 f . 
    . . . f 2 2 4 2 2 2 2 2 2 2 f . 
    . . . f 2 2 4 2 2 2 2 2 2 2 f . 
    . . . f 2 c 2 4 4 2 2 2 c 2 f . 
    . . . e 2 c e c c c c e c 2 e . 
    . . . e 2 e c b b b b c e 2 e . 
    . . . e 2 e b b b b b b e 2 e . 
    . . . e e e e e e e e e e e e . 
    . . . f e d e e e e e e d e f . 
    . . . f e 2 d e e e e d 2 e f . 
    . . . f f e e e e e e e e f f . 
    . . . . f f . . . . . . f f . . 
    `, SpriteKind.Player)
controller.moveSprite(Car, 100, 0)
scene.setBackgroundImage(img`
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    ..........................................fffffffffffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffff...............................................
    `)
scene.setBackgroundColor(7)
let Tree = sprites.create(img`
    .............6666...............
    ..........666667766.6666........
    .........677777777767776........
    ......66667775577757777666......
    .....677666675557557776777666...
    .....6776777775555577777766776..
    ...66666777777775777777766666...
    .66667767777755757555777776776..
    6666777677775577557555777767766.
    .6667767777777775577777777767666
    .c6766777677777775777777677766..
    cc77666667777777777777777666666c
    cc76666677777777777777777766776c
    c6666776777777777777766677666776
    66667766667776777767767766766666
    ccc76677677776677766767776776ccc
    cc7766776777677677676667767766cc
    .666c676667677766667766666666cc.
    .ccc66676666776666677677666cccc.
    ...ccc77c6767666676676677666ccc.
    ...cc676c7766676677666666c666cc.
    ....c6cc676c6677677c66c666ccc...
    ....ccccc6c66667667cc6ccc6ccc...
    ......ccccc66c66c66cccccccc.....
    .......cc.cc6c6ccc6cccc.cc......
    ...........cccccccccc...........
    .............feeeeee............
    ............feeeeeefe...........
    .........eeeeefeeeffee..........
    ............ffffeef..ee.........
    ...............fee..............
    ................e...............
    `, SpriteKind.object)
game.onUpdateInterval(1000, function () {
    info.changeScoreBy(1)
})
forever(function () {
    Tree.setPosition(130, 21)
    pause(100)
    Tree.setPosition(130, 41)
    pause(100)
    Tree.setPosition(130, 61)
    pause(100)
    Tree.setPosition(130, 81)
    pause(100)
    Tree.setPosition(130, 101)
    pause(100)
    Tree.setPosition(17, 21)
    pause(100)
    Tree.setPosition(17, 41)
    pause(100)
    Tree.setPosition(17, 61)
    pause(100)
    Tree.setPosition(17, 81)
    pause(100)
    Tree.setPosition(17, 101)
    Car_Crash = sprites.create(img`
        . . . . . . . 8 8 8 8 8 . . . . 
        . . . . . 8 8 6 6 6 6 6 8 . . . 
        . . . . 8 8 6 6 6 6 6 6 6 8 . . 
        . . . . 8 9 7 6 6 6 6 6 7 b 8 . 
        . . 8 8 9 9 7 7 6 6 6 6 7 9 b 8 
        . 8 6 6 9 9 7 7 7 6 6 6 7 9 9 8 
        8 6 6 6 9 9 6 7 7 7 7 7 6 9 9 8 
        8 6 6 6 9 9 8 8 8 8 8 8 8 9 9 8 
        8 6 6 6 9 b 8 b b b 8 b 8 b 9 8 
        8 6 8 8 8 8 b b b b 8 b b 8 b 8 
        8 8 3 3 8 8 6 6 6 6 8 6 6 8 8 8 
        8 3 3 8 8 8 8 8 8 8 8 8 8 8 8 8 
        8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
        8 8 8 8 f f f 8 8 8 8 f f f 8 8 
        . 8 8 f b c c f 8 8 f b c c f . 
        . . . . b b f . . . . b b f . . 
        `, SpriteKind.Enemy)
    Car_Crash.setPosition(1000, 0)
})
forever(function () {
    pause(5000)
    Car_Crash.setPosition(randint(50, 100), 0)
    Car_Crash.setVelocity(0, 200)
    pause(500)
    Car_Crash.setPosition(1000, 0)
})
